In [18]:
!pip install word2number

In [19]:
import pandas as pd
import numpy as np

df = pd.read_csv('linear_reg_predict_salaryEmployees.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [20]:
from IPython.display import display, HTML
display(HTML('<h1> First we do Data Preprocessing: Fill NA values with median value of a column</h1>'))

In [33]:
# !pip install word2number  # converting strings to number integers
import math, pandas as pd
from word2number import w2n   
df.experience = df.experience.fillna("zero")
# df['experience'] = df['experience'].apply(w2n.word_to_num)
df['experience']

df['test_score(out of 10)']
median_score = math.floor(df['test_score(out of 10)'].median())
median_score == 8.0
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(median_score)
df['test_score(out of 10)']

0     8.0
1     8.0
2     6.0
3    10.0
4     9.0
5     7.0
6     8.0
7     7.0
Name: test_score(out of 10), dtype: float64

In [31]:
display(HTML('<h1> Now starting with Linear Regression </h1>'))
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [34]:
from sklearn import linear_model
reg = linear_model.LinearRegression()
df['salary($)']
reg.fit(df.drop('salary($)',axis='columns'),df['salary($)']) 
# another way to get all the features of hiring process ,
# ( taking columns experience, test_score, interview_score ) 
# and giving target, df['salary'] ->  which we need to predict


LinearRegression()

In [35]:
display(HTML('<h1> Now we get coef_, intercept_,  </h1>'))

In [36]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [37]:
reg.intercept_

17737.263464337688

In [38]:
display(HTML('<h1> Using coef, intercept , we can predict salary of any individual </h1>'))

In [39]:
reg.predict([[2,10,10]])

C:\Users\tushar.m\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([63872.63464338])

In [45]:
display(HTML('<h1>Saving the Model using Pickle Module </h1>'))

In [48]:
import pickle
with open('model_pickle',"wb") as f:
    pickle.dump(reg,f)
    # Model refers to reg  # == LinearRegression()

In [49]:
display(HTML('<h1>Load the Model using Pickle Module </h1>'))

In [50]:
with open('model_pickle','rb') as f:
    model = pickle.load(f)

In [53]:
model.predict([[2,10,10]])

C:\Users\tushar.m\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([63872.63464338])

In [58]:
display(HTML('<h1>Saving the Model using joblib Module </h1>'))

In [57]:
# Difference between joblib and pickle
#  - if using a lot of np arrays, joblib is more beneficial 
import joblib
joblib.dump(model,'model_joblib')

['model_joblib']

In [63]:
display(HTML('<h1>Load the Model using Joblib Module </h1>'))

In [62]:
model_= joblib.load("model_joblib")
model_.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])