In [4]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [3]:
from IPython.display import display, HTML
display(HTML('<h1>Using K fold we will evaluate Each model </h1>'))


In [20]:
lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9518518518518518

In [19]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)  # with gamma='auto' it performed poorly

0.9777777777777777

In [18]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9611111111111111

In [22]:
from IPython.display import display, HTML
display(HTML('<h1> K Fold cross validation Basic example </h1>'))


In [23]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)  # using 3 folds or 3 stacks for testing the DATA 
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [26]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print( test_index, train_index)

    # so here 3 folds where 
#     1 fold test = [0 1 2] [3 4 5 6 7 8]
#     2 fold test = [3 4 5] [0 1 2 6 7 8]
#     3 fold test = [6 7 8] [0 1 2 3 4 5]

[0 1 2] [3 4 5 6 7 8]
[3 4 5] [0 1 2 6 7 8]
[6 7 8] [0 1 2 3 4 5]


In [28]:
def get_score(model, X_train, X_test, y_train, y_test):
    """ here get_score will 
    check score for each model """
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [31]:
get_score(LogisticRegression(), X_train, X_test, y_train, y_test)
get_score(SVC(), X_train, X_test, y_train, y_test)
get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test)

C:\Users\tushar.m\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9611111111111111

In [ ]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []    # score of logistic regression
scores_svm = []         # score of  Support Vector Machine
scores_rf = []          # score of Random forest regression

for train_index, test_index in folds.split( digits.data, digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [41]:
display(HTML("""<h1># cross_val_score function
# -  Here we dont need to  manually run the loop for each train data and test data like we did in above code
# -  using cross val_score , it will automatically run the test data for each partition  </h1>"""))

In [33]:
# cross_val_score function
# -  Here we dont need to  manually run the loop for each train data and test data 
# -  using cross val_score , it will automatically run the test data for each partition 
from sklearn.model_selection import cross_val_score
# Logistic regression model performance using cross_val_score

cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target, cv=3) 
# here cv is TOTAL FOLDS in kfold testing 


array([0.89482471, 0.95325543, 0.90984975])

In [37]:
# svm model performance using cross_val_score

cross_val_score(SVC(gamma='auto'), digits.data, digits.target,cv=3)

array([0.38063439, 0.41068447, 0.51252087])

In [38]:
# random forest performance using cross_val_score

cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target,cv=3)

array([0.92821369, 0.95158598, 0.9148581 ])

In [43]:
# Parameter tunning using k fold cross validation
scores1 = cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target, cv=10)
np.average(scores1)

0.9426846679081315